services:

  # app:
  #   image: jraay12/multi-tenant-helpdesk-api:1.0.0
  #   container_name: multi_tenant_helpdesk
  #   restart: unless-stopped
  #   ports:
  #     - "3010:3000"
  #   env_file:
  #     - ./.env
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   command: sh -c "npx prisma migrate deploy && node dist/server.js"

  db:
    image: mysql:8.0
    container_name: saas_booking_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      MYSQL_DATABASE: booking-db
    ports:
      - "3306:3306"
    volumes:
      - saas_booking_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pqwerty"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: saas_booking_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: "qwerty"
    depends_on:
      db:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq_broker
    restart: always
    hostname: my-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=securepassword123
      - RABBITMQ_DEFAULT_VHOST=my_vhost
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia/
      - rabbitmq_logs:/var/log/rabbitmq

volumes:
  saas_booking_data:
  rabbitmq_data:
  rabbitmq_logs: